spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nakhdb
    username: pass
    password: 1212

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false #DB-ile is bitdikde session baglanir
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
        show_sql: true
        dialect:  org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nakhinvest@gmail.com}
    password: ${MAIL_PASSWORD:psrjgvmijljpmiue}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8


logging:
  level:
    org.springframework: info
    org.hibernate: info

server:
  port: 8081

jwt:
  key: cn5N5rbQ1ruPW7ZEbjV6XMToIHyhG9KgHbvZedQahvjqqU3Kv9tv8X6gK289IXVXHUSVhKbjCgyny0SVOBOSg==
  access-token-expiration: 900_000

image:
  upload:
    dir: C:/Users/nihada/images
    max-size: 10485760 # 10

pdf:
  upload:
    dir: C:/Users/nihada/pdf
    max-size: 10485760 # 10 M


base:
  url:
    image: https://nakhinvest.az
    pdf: https://admin.nakhinvest.az