spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nakhdb
    username: pass
    password: 1212

  jpa:
    hibernate:
      ddl-auto: create-drop

    open-in-view: false #DB-ile is bitdikde session baglanir
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
        show_sql: true
        dialect:  org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB


logging:
  level:
    org.springframework: info
    org.hibernate: info

server:
  port: 8081

jwt:
  key: cn5N5rbQ1ruPW7ZEbjV6XMToIHyhG9KgHbvZedQahvjqqU3Kv9tv8X6gK289IXVXHUSVhKbjCgyny0SVOBOSg==
  access-token-expiration: 300000
  refresh-token-expiration: 18000000
image:
  upload:
    dir: C:/Users/nihada/images

base:
  url: http://localhost:8081